author: Paulo Ortins
title: Paulo Ortins 
subtitle: C#, Xamarin and More
gravatar_url: http://www.gravatar.com/avatar/a1c6e240931b44f7f4b21492232cd3fc.png

paginate: 10
markdown: kramdown
highlighter: pygments 

permalink: /:year/:month/:day/:title/

excerpt_separator: <!--more-->

# Disqus Comments
disqus_short_name: pauloortins
disqus_show_comment_count: true

#github user
github_repo_url: https://github.com/pauloortins/pauloortins.github.io/

#social
email: paulo.ortins@gmail.com
twitter_user: pauloortins
github_user: pauloortins
subscribe_rss: http://feeds.feedburner.com/pauloortins
addthis_profile_id: ra-5521b8af4f6fda8c 

#analytics
google_analytics_tracking_id: UA-40530191-1

#blog info
name: Paulo Ortins .NET
description: Want to know more about Xamarin, .NET and software development? You came to the right place!
url: http://pauloortins.com
