author: Paulo Ortins
title: Paulo Ortins
gravatar_url: http://www.gravatar.com/avatar/a1c6e240931b44f7f4b21492232cd3fc.png

paginate: 20
name: Your New Jekyll Site
markdown: kramdown
pygments: true

permalink: /:year/:month/:day/:title/

excerpt_separator: ""

# Disqus Comments
disqus_short_name: pauloortins
disqus_show_comment_count: true

#github user
github_repo_url: https://github.com/pauloortins/pauloortins.github.io/
